# Generated by Django 5.1.4 on 2025-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
